spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: ms-account-balance
      auto-offset-reset: earliest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://account-db:3306/account
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl