spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: wallet
      auto-offset-reset: earliest
  datasource:
    username: account
    url: jdbc:postgresql://account-db:5432/account
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl