version: '3.6'

services:
  account-db:
    image: postgres:13.1-alpine
    container_name: account-db
    restart: always
    environment:
      POSTGRES_DB: account
      POSTGRES_USER: account
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  account-app: 
    container_name: account-app
    build: 
      context: ./ms-account-balance       
    ports:
      - 3003:8080
    depends_on:
      - account-db
    command: sh -c "dockerize -wait tcp://account-db:5432 -timeout 240s -wait-retry-interval 2s && java -jar balance.jar"

  wallet-db:
    image: mysql:5.7
    container_name: wallet-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_USER: wallet
      MYSQL_PASSWORD: password
    ports:
      - 3308:3306
 
  wallet-app: 
    container_name: wallet-app
    build: 
      context: ./ms-wallet-core            
    volumes:
      - ./ms-wallet-core:/app
    ports:
      - 8080:8080
    depends_on:
      - wallet-db   
    command: sh -c "dockerize -wait tcp://wallet-db:3306 -timeout 240s -wait-retry-interval 2s && go run cmd/walletcore/main.go -b 0.0.0.0"

  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    container_name: zookeeper
    environment:
      TZ: Sao_Paulo/Brazil
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: "confluentinc/cp-kafka:latest"
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      TZ: Sao_Paulo/Brazil
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-topics-generator:
    image: "confluentinc/cp-kafka:latest"
    container_name: kafka-topics-generator
    depends_on:
      - kafka
    command: >
      bash -c 
        "sleep 10s &&
        kafka-topics --create --topic=accounts --if-not-exists --bootstrap-server=kafka:9092 &&
        kafka-topics --create --topic=transactions --if-not-exists --bootstrap-server=kafka:9092 &&
        kafka-topics --create --topic=balances --if-not-exists --bootstrap-server=kafka:9092"    
