# Cria cliente
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Zeca",
    "email": "john@j.com"
}

### Cria conta

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "dce688c6-4cd4-42e1-83d8-190960be1026"
}

### Transação 
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "cc8338e5-9210-44bb-a4b4-18a8fa8b9233",
    "account_id_to": "b0eaf769-ec40-4264-9784-7bcc7588cd9a",
    "amount": 10
}

### Exibe saldo da 1a conta
GET http://localhost:3003/balances/cc8338e5-9210-44bb-a4b4-18a8fa8b9233  HTTP/1.1

### Exibe saldo da 2a conta
GET http://localhost:3003/balances/b0eaf769-ec40-4264-9784-7bcc7588cd9a HTTP/1.1