
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Zeca",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "998fdc71-dff1-4610-b27b-3ccb655e15f4"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "cc8338e5-9210-44bb-a4b4-18a8fa8b9233",
    "account_id_to": "b0eaf769-ec40-4264-9784-7bcc7588cd9a",
    "amount": 10
}